name: time_management
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_dart: ^1.3.3
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  firebase_storage: ^12.4.4

  # Authentication
  google_sign_in: ^6.3.0

  # Notifications
  flutter_local_notifications: ^19.1.0  # Sử dụng phiên bản tương thích

  # UI & Animations
  animations: ^2.0.8
  lottie: ^3.3.1
  animated_splash_screen: ^1.3.0
  fl_chart: ^0.71.0
  flutter_svg: ^2.0.17

  # Calendar & Localization
  table_calendar: ^3.0.9
  intl: ^0.19.0
  easy_localization: ^3.0.3

  # State Management
  flutter_bloc: ^9.1.0
  bloc_concurrency: ^0.3.0

  # Utilities
  android_alarm_manager_plus: ^4.0.7
  flutter_tts: ^4.2.2
  wakelock_plus: ^1.2.11
  shared_preferences: ^2.2.2
  nb_utils: ^7.1.4

  # Image Picker
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  http: ^1.3.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/images/
    - assets/svgs/
    - assets/translations/

  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Light.ttf
        - asset: assets/fonts/Sora-Regular.ttf
        - asset: assets/fonts/Sora-Medium.ttf
          weight: 300
        - asset: assets/fonts/Sora-Bold.ttf
        - asset: assets/fonts/Sora-ExtraLight.ttf
        - asset: assets/fonts/Sora-ExtraBold.ttf
          weight: 700