// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQZXuCIMAXkJ4SdTfgaIoVavpKCK3TIOQ',
    appId: '1:1008359161619:web:ccbff4c6fdfa05faa1e4e6',
    messagingSenderId: '1008359161619',
    projectId: 'time-6bd60',
    authDomain: 'time-6bd60.firebaseapp.com',
    storageBucket: 'time-6bd60.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCip9oZKih02kh3YmX6A_IFhpeUMQc9S6M',
    appId: '1:1008359161619:android:cd0f8babab4c490ea1e4e6',
    messagingSenderId: '1008359161619',
    projectId: 'time-6bd60',
    storageBucket: 'time-6bd60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkuRWt8LolyvJKKJTdjeCAS9FQtHA3hek',
    appId: '1:1008359161619:ios:6ba958e48f45125ea1e4e6',
    messagingSenderId: '1008359161619',
    projectId: 'time-6bd60',
    storageBucket: 'time-6bd60.firebasestorage.app',
    androidClientId: '1008359161619-bh42lll5057ctobqp434dcsot2ut27sg.apps.googleusercontent.com',
    iosClientId: '1008359161619-13t4982n3m43g9ipgtetqjvrm90dsdes.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudTime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkuRWt8LolyvJKKJTdjeCAS9FQtHA3hek',
    appId: '1:1008359161619:ios:6ba958e48f45125ea1e4e6',
    messagingSenderId: '1008359161619',
    projectId: 'time-6bd60',
    storageBucket: 'time-6bd60.firebasestorage.app',
    androidClientId: '1008359161619-bh42lll5057ctobqp434dcsot2ut27sg.apps.googleusercontent.com',
    iosClientId: '1008359161619-13t4982n3m43g9ipgtetqjvrm90dsdes.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudTime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQZXuCIMAXkJ4SdTfgaIoVavpKCK3TIOQ',
    appId: '1:1008359161619:web:e204a8a2b8cea944a1e4e6',
    messagingSenderId: '1008359161619',
    projectId: 'time-6bd60',
    authDomain: 'time-6bd60.firebaseapp.com',
    storageBucket: 'time-6bd60.firebasestorage.app',
  );
}
